### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by kamalmarhubi**

### CODE REVIEW

**Comment by paulproteus** [comment]
Hi @kamalmarhubi ! Nice to e-see you here.

I'm going to take the liberty of merging this typo fix right now. Thanks for submitting it!

**Comment by kamalmarhubi** [comment]
@paulproteus thanks :-)

**Comment by paulproteus** [comment]
You're welcome! And the black border on the avatar looks really good here on GitHub!

**Comment by kamalmarhubi** [comment]
:-) I'll have to thanks the peeps at the Recurse Center! (And also figure out how to get a higher res copy of it...)

**Pull request merged**
