### PR TITLE
Allow trailing commas in parenthesized and bracketed lists.

### PR DESCRIPTION
**Pull request by zarvox**
Add tests to verify this behavior.

Also, include `schema-parser-test.c++` in the CMake and autotools test suites.  Somehow it got left out.

### CODE REVIEW

**Comment by kentonv** [comment]
I hate to say this, but I think the right place to make this edit is actually in `lexer.c++`, around line 159-ish. That's the same place where we handle differentiating an empty list from a one-item list, which similarly detects has to detect that there are no tokens in the list item.

**Comment by zarvox** [comment]
Ahh, yeah, I wasn't sure if the lexer should strip out the commas as though they were never there, or if it should detect them, and then let the parser remove them instead.  But I'll go ahead and revamp this patchset so it's the lexer stripping things out instead.

**Comment by zarvox** [comment]
Okay, reworked to have the lexer detect an empty final list item.

**Comment by paulproteus** [comment]
I just want to say:

+1
​

**Pull request merged**
